### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by scooper1** [lmagyar/homeassistant-addon-portainer-beta#1]
Can't install lmagyar/amd64-addon-portainer:2.1.1-rc01: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.1.1-rc01&fromImage=lmagyar%2Famd64-addon-portainer&platform=linux%2Famd64: Not Found ("manifest for lmagyar/amd64-addon-portainer:2.1.1-rc01 not found: manifest unknown: manifest unknown")

getting the above error message

**Comment by lmagyar** [comment]
Please use the **non beta repo** (https://github.com/lmagyar/homeassistant-addon-portainer) with the **released** v2.1.1, this beta repo is for myself to experiment, test, and after it works I delete even the images from docker. :)

And that error message shows, that I've deleted the beta image.

**Comment by scooper1** [comment]
thanks 
was looking for a portainer update and did not see there was a non-beta
maybe a message to use the non-beta version on the beta readme would help
thanks non-beta version running nicely

**Comment by lmagyar** [comment]
You are right! I've added a message with a big red STOP sign that this is only a beta repo, and I will add it to all my beta repos. :)
